# module purge
# module load gnutools
# module load intel/2016.3.210 openmpi_ib/1.8.4
packages:
  all:
    compiler: [intel]
    providers:
      blas: [intel-mkl]
      lapack: [intel-mkl]
      mkl: [intel-mkl]
      mpi: [openmpi]
      scalapack: [intel-mkl]

  intel-mkl:
    buildable: False
    paths:
      # module show intel/2016.3.210
      # MKLROOT
      intel-mkl@2016.3.210: /opt/intel/2016.3.210/compilers_and_libraries_2016.3.210/linux/mkl
  openmpi:
    buildable: False
    modules:
      openmpi@1.8.4: openmpi_ib/1.8.4

  fftw:
    buildable: False
    modules:
      fftw@2.1.5~double~float+mpi~openmp: fftw/2.1.5
      fftw@3.3.4+double+float+mpi+openmp: fftw/3.3.4
  gsl:
    buildable: False
    modules:
      gsl@1.16: gsl/1.16
  hdf5:
    modules:
      hdf5@1.8.14+mpi: hdf5/1.8.14
  libtool:
    buildable: False
    modules:
      libtool: gnutools
