compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    # https://portal.tacc.utexas.edu/user-guides/stampede2#building-performance-architecture
    flags:
      cflags: -xCORE-AVX2 -axCORE-AVX512,MIC-AVX512 -O3
      cxxflags: -xCORE-AVX2 -axCORE-AVX512,MIC-AVX512 -O3
      fflags: -xCORE-AVX2 -axCORE-AVX512,MIC-AVX512 -O3
      ldflags: -xCORE-AVX2 -axCORE-AVX512,MIC-AVX512
    modules: [intel/18.0.2]
    operating_system: centos7
    paths:
      cc: /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/icc
      cxx: /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/icpc
      f77: /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/ifort
      fc: /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/ifort
    spec: intel@18.0.2
    target: x86_64
