# module reset
# module load intel/18.0.2 impi/18.0.2
packages:
  all:
    compiler: [intel]
    providers:
      blas: [intel-mkl]
      lapack: [intel-mkl]
      mkl: [intel-mkl]
      mpi: [intel-mpi]
      scalapack: [intel-mkl]

  intel-mkl:
    buildable: False
    paths:
      # module show intel/18.0.2
      # MKLROOT
      intel-mkl@2018.2.199: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl
  intel-mpi:
    buildable: False
    modules:
      intel-mpi@2018.2.199: impi/18.0.2

  fftw:
    buildable: False
    modules:
      fftw@3.3.8+double+float+mpi+openmp: fftw3/3.3.8
    paths:
      # fftw2/2.1.5 TACC_FFTW2_DIR
      fftw@2.1.5+double+float+mpi+openmp: /home1/apps/intel18/impi18_0/fftw2/2.1.5
  hdf5:
    buildable: False
    modules:
      hdf5@1.10.4: phdf5/1.10.4

  gizmo:
    variants: +mpi_in_place
